let suggestions = [
    
    "Iron Man",
    "The Incredible Hulk",
    "Iron Man 2",
    "Thor",
    "Captain America: The first Avenger",
    "Avengers",
    "Iron Man 3",
    "Thor: The Dark World",
    "Captain America: Winter Soldier",
    "Guardians Of The Galaxy",
    "Avengers: Age of Ultron",
    "Ant Man",
    "Captain America: Civil War",
    "Doctor Strange",
    "Guardians of the Galaxy: Vol.2",
    "Spider Man: HomeComing",
    "Thor 3: Ragnarok",
    "Black Panther",
    "Avengers: Infinity War",
    "Ant Man & Wasp",
    "Captain Marvel",
    "Avengers: Endgame",
    "SpiderMan: Far From Home",
    "Wanda Vision",
    "Falcon And The Winter Soldier",
    "Loki",
    "Black Widow",
    "What If...?",
    "Shang Chi: Legend of the Ten Rings",
    "Eternals",
    "Hawkeye",
    "SpiderMan: No Way Home",

];